### ISSUE TITLE
api docs question

### ISSUE THREAD

**Issue by motss** [stampery/node#5]
> For stamping a SHA3-512 hash, you only have to make a call to the stamp method of our API, as seen in the examples to the right.

Since not being able to file an issue at your api docs repo, I would like ask if there is a typo in your documentation. Thanks for creating such great tool.

I can't find the `stamp` method being used in the example provided. Do you mean the `hash` method like `stampery.hash`?

The following image shows a screenshot of a portion of your API doc and in the last paragraph, it says `stamp` method but there is no `stamp` in the example on the rightmost.

![where_is_stamp_method](https://cloud.githubusercontent.com/assets/10607759/16951779/121555f4-4df9-11e6-95d0-482803bd8a61.PNG)

**Comment by hems** [comment]
@motss the documentation was updated recently, i believe it's way clearer, have a look!

Regarding your question,  the stamp method is now available as you can [see here](https://github.com/stampery/node/blob/master/src/stampery.coffee#L85-L88) and it works as a wrapper to the current HTTP API.

The hash method is now available as a synchronous function as you [can see here](https://github.com/stampery/node/blob/master/src/stampery.coffee#L30-L34).

I hope that helps.

@aesedepece let me know if something isn't right on my answer.

peace
